name:                RTCNs
version:             0.1.0.0
github:              "EgorLappo/RTCNs"
license:             BSD3
author:              "Egor Lappo"
maintainer:          "egor@ccrma.stanford.edu"
copyright:           "Copyright: (c) 2023 Egor Lappo"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/EgorLappo/RTCNs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  RTCNs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RTCNs

tests:
  RTCNs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RTCNs
